### ISSUE TITLE
Publishing javadoc

### ISSUE THREAD

**Issue by hotchemi** [cookpad/puree-android#40]
Thanks for your great library guys.

I think publishing javadoc makes the library more understandable.
Actually square's [moshi](https://github.com/square/moshi) just do it with their [gh-pages branch](http://square.github.io/moshi/).
How do you think about of it?

**Comment by gfx** [comment]
Looks good. Can you make a pull-request?

**Comment by hotchemi** [comment]
@gfx 
I'm really sorry for the delay.
I sent one PR so could you review it?
I'm gonna close this issue.
