### ISSUE TITLE
Puree artifact jar is empty

### ISSUE THREAD

**Issue by chibatching** [cookpad/puree-android#68]
4.1.3 is released, but the artifact delivered from maven server is empty, so we can't use any classes and library.
![image](https://user-images.githubusercontent.com/7804631/59738625-dce41780-929c-11e9-84ce-7c0ca8e4509b.png)

**Comment by litmon** [comment]
Thanks for reporting, and PullRequest.
When I was investigating this issue, I found the problem that `classes.jar` moved other directory.

- before
  - puree/build/intermediates/classes/release/classes.jar
- after
  - puree/build/intermediates/packaged-classes/release/classes.jar

So the problem will be fixed when the path fixed(below code). You don't need to make aar publishing.
https://github.com/cookpad/puree-android/blob/af20eb635a0a17e11e35bd5e8f4972979360ebec/puree/build.gradle#L91

**Comment by chibatching** [comment]
Why do you not use AAR?
AAR is a standard library format for Android. It brings some benefit like including AndroidManifest to restrict SDK version.
 
In my opinion, if the library is scoped only Android, aar is better than jar.
Of course, if you prefer jar than aar, I respect it.

**Comment by kazy1991** [comment]
直ったと思ったら直ってなかった。 ごめんなさい近い内に直します。aarにするかは検討させてください
